title: "Muhammad Bilal Saad Blog"
author: "Muhammad Bilal Saad"
description: "Personal portfolio and blog"
baseurl: ""
url: "https://Muhammad-BilalSaad.github.io"
lang: "en"
permalink: /:title/
show_sidebar: false
show_frame: true
show_excerpts: true
show_minimal: false

navigation:
  - {file: "index.md", sidebaricon: home}
  - {file: "about.md", sidebaricon: address-card}
  - {file: "journey.md", sidebaricon: book-open}
  - {file: "contact.md", sidebaricon: envelope}

external:
  - {title: Mail, icon: envelope, url: "mailto:your-email@example.com"}
  - {title: Github, icon: github, url: "https://github.com/Muhammad-BilalSaad"}

plugins:
  - jekyll-feed
  - jekyll-paginate
