title: " Portfolio"
author: "BilalSaad"
description: "My Journey, Blog & Portfolio Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout Settings
show_excerpts: false
show_frame: true
show_sidebar: false
show_minimal: false

# Navigation Menu (TOP MENU)
navigation:
  - {file: "index.html", title: "Home"}
  - {file: "about.md", title: "About Me"}
  - {file: "journey.md", title: "My Journey"}
  - {file: "contact.md", title: "Contact"}

# External Links
external:
  - {title: Email, icon: envelope, url: "mailto:u1247874@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/Muhammad-BilalSaad"}

# Plugins
plugins:
  - jekyll-feed
